/**
 * *************************************************************************************************************
 * @file Isp_Iap_Uart.h
 * @author BH_CodeGenerator
 * @version 0.1
 * @date 2022-04-01
 * @warning <!--auto generated by Tools, do not modify or add anything, otherwise, your change will be lost!!! -->
 * @brief all the functions prototypes for Isp_Iap_Uart firmware library
 * MCU / CFG Ver. :BH66F2475/1.7
 * Version = 1.0.0

 * *************************************************************************************************************
 *  @attention
 *
 *  Firmware Disclaimer Information
 *
 *  1. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *     code, which is supplied by BEST HEALTH ELECTRONIC Inc., (hereinafter referred to as BestHealth) is the
 *     proprietary and confidential intellectual property of BestHealth, and is protected by copyright law and
 *     other intellectual property laws.
 *
 *  2. The customer hereby acknowledges and agrees that the program technical documentation, including the
 *     code, is confidential information belonging to BestHealth, and must not be disclosed to any third parties
 *     other than BestHealth and the customer.
 *
 *  3. The program technical documentation, including the code, is provided and for customer reference
 *     only. After delivery by BestHealth, the customer shall use the program technical documentation, including
 *     the code, at their own risk. BestHealth disclaims any expressed, implied or statutory warranties, including
 *     the warranties of merchantability, satisfactory quality and fitness for a particular purpose.
 *
 *  <h2><center>Copyright (C) BEST HEALTH ELECTRONIC Inc. All rights reserved</center></h2>
 */
/* Define to prevent recursive inclusion -------------------------------------------------------------------*/
#ifndef _IAP_ISP_H_
#define _IAP_ISP_H_

/* Includes ------------------------------------------------------------------------------------------------*/
#include "..\board\BoardCfg.h"
#include <stdint.h>

/* User define ---------------------------------------------------------------------------------------------*/
// !!! If you need to modify, please redefine the modified content in the BoardCfg.h file. This file is automatically generated and all modifications may be overwritten.
#ifndef FH_CLOCK_FREQ
    #define FH_CLOCK_FREQ 4000000    //! <Set system frequency, currently supported settings are 4000000,8000000,12000000
#endif
#ifndef SYS_CLOCK_FREQ
    #define SYS_CLOCK_FREQ 4000000    //! <Set system frequency, currently supported settings are 4000000,8000000,12000000
#endif
#ifndef UART_BAUD_RATE
    #define UART_BAUD_RATE 9600    //!< 300(Only 4M),1200,2400,4800,9600,19200,38400(Only 8M),57600(Only 12M),250000
#endif
#ifndef PROM_AP_ADDRESS_START
    #define PROM_AP_ADDRESS_START 0x0400    // This address is not recommended to be changed: 1K bootLoader address end
#endif

/* Exported Variables --------------------------------------------------------------------------------------*/
extern const uint8_t bootLoader_Ver[3];    // version

/* Exported functions --------------------------------------------------------------------------------------*/
void BootLoader_Start(void);

#endif